### ISSUE TITLE
세로로 긴 화면비 사용 중 로고가 x로 되돌아가는 문제가 있습니다.

### ISSUE THREAD

**Issue by dirueg** [eunjae-lee/yet-twitter#1]
안녕하세요! 정말 좋은 기능 감사합니다!
크롬 브라우저를 사용하고 있구요, 브라우저를 세로로 길게 모바일 환경과 유사한 비율로 트위터를 사용하는데 새 트윗 작성하기나, 프리미엄 가입 등 화면 전체가 가려지는 경우에 트위터 로고가 X로 돌아가는 문제가 있습니다.  새로고침하면 다시 돌아오긴 하지만 약간 신경 쓰여서 제보해요.

**Comment by eunjae-lee** [comment]
@dirueg 안녕하세요! 제보 감사합니다. 왔다 갔다 하면서 되돌아가는군요. 살펴볼게요 :)
